simplesocial/accounts/urls.py
from django.urls import path
from accounts.views import  SignUpView
from django.contrib.auth import views as auth_views



app_name = 'accounts'
urlpatterns = [
     path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', SignUpView.as_view(), name='signup'),

]

simplesocial/groups/urls.py
from django.urls import path, re_path
from groups.views import CreateGroupView, ListGroupView, DetailGroupView
from groups import views

app_name = 'groups'
urlpatterns = [
     path('', ListGroupView.as_view(), name="list"),
    path('create/', CreateGroupView.as_view(), name="create"),
    re_path(r"^posts/in/(?P<slug>[-\w]+)/$",views.DetailGroupView.as_view(), name="single"),
    re_path(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    re_path(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),

 ]

simplesocial/posts/urls.py
from django.urls import path, re_path

from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    re_path(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    re_path(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    re_path(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from simplesocial.views import IndexView, Testpage, Thankspage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('test/', Testpage.as_view(), name='test'),
    path('thanks/', Thankspage.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls')),
    path('groups/', include('groups.urls')),
    path('posts/', include('posts.urls'))


]

simplesocial/templates/base.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

</head>
  <body>

      <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <div class="container">
        <img src="{% static 'images/star.png' %}" width="60" height="60" class="d-inline-block align-top" alt="">
        <h1><a class="navbar-brand" href="{% url 'index' %}"><strong>Star Social</strong></a></h1>

          {% if user.is_authenticated%}
          <ul class="navbar-nav ml-auto">
            <li><a class="nav-link" href="{% url 'posts:create' %}">Create Post</a></li>
            <li><a class="nav-link" href="{% url 'groups:list' %}">Groups</a></li>
            <li><a class="nav-link" href="{% url 'accounts:logout' %}"><span><i class="fa fa-sign-out"></i></span> Log out</a></li>
          </ul>

          {%else%}
          <ul class="navbar-nav ml-auto">
            <li><a class="nav-link" href="{% url 'groups:list' %}">Groups</a></li>
            <li><a class="nav-link" href="{% url 'accounts:login' %}"><span><i class="fa fa-sign-in"></i></span> Log In</a></li>
            <li><a class="nav-link" href="{% url 'accounts:signup' %}"><span><i class="fa fa-user"></i></span> SignUp</a></li>


          </ul>


          {%endif%}
          </div>

      </nav>


<p></p>
<p></p>
    <div class="container mycontent">
      {% block body_block %}
      {% endblock %}

    </div>
    <canvas id="canvas"></canvas>

  </body>
  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>

</html>

simplesocial/templates/index.html
{% extends 'base.html' %}
{% block body_block %}

<div class="jumbotron">
  <div class="container">

      <h1>Welcome to Star Social, </h1>
      <h2>An Outer Space Fan Community Site!</h2>
      <p></p>
      <p></p>
    <ul>
      <p></p>
      <li><h4>Users can create groups on various topics (e.g. SpaceX, Pluto, NASA, etc.. )</h4>
      </li>
      <li><h4>Users can then create posts in the groups</h4>
      </li>
      <li><h4>Users can also join and leave groups</h4>
      </li>

    </ul>
  </div>

</div>
<style >
  .jumbotron{
    background-color: black;
  }
</style>

{% endblock %}

simplesocial/templates/test.html
{% extends "base.html" %}
{% block body_block %}
<h1>Hello, {{user.username}}</h1>
<h2>You are now logged in</h2>
{% endblock %}

simplesocial/templates/thanks.html
{% extends "base.html" %}
{% block body_block %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}