simplesocial/groups/urls.py
from django.urls import path, re_path
from groups.views import CreateGroupView, ListGroupView, DetailGroupView
from groups import views

app_name = 'groups'
urlpatterns = [
     path('', ListGroupView.as_view(), name="list"),
    path('create/', CreateGroupView.as_view(), name="create"),
    re_path(r"^posts/in/(?P<slug>[-\w]+)/$",views.DetailGroupView.as_view(), name="single"),
    re_path(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    re_path(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),

 ]

simplesocial/posts/urls.py
from django.urls import path, re_path

from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    re_path(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    re_path(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    re_path(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from simplesocial.views import IndexView, Testpage, Thankspage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('test/', Testpage.as_view(), name='test'),
    path('thanks/', Thankspage.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls')),
    path('groups/', include('groups.urls')),
    path('posts/', include('posts.urls'))


]

simplesocial/groups/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils.text import slugify

import misaka

from django.contrib.auth import get_user_model
User = get_user_model()


from django import template
register = template.Library()



class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="GroupMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships", on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

simplesocial/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import TemplateView, CreateView, ListView, DetailView
from . import models
from django.views import generic
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from groups.models import Group,GroupMember
from . import models
# Create your views here.
class CreateGroupView(CreateView, LoginRequiredMixin):
    model = models.Group
    fields = ('name', 'description')

class ListGroupView(ListView, LoginRequiredMixin):
    model = models.Group
    fields = ('name', 'description')

class DetailGroupView(DetailView, LoginRequiredMixin):
    model = models.Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

simplesocial/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block body_block %}

<div class="container">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>

{% endblock %}

simplesocial/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}


<h1>{{group.name}}
<div class="content">


      {% if user in group.members.all %}
        <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-danger"><span><i class="fa fa-times"></i></span> Leave this group</a>
      {% else %}
        <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-success"><span><i class="fa fa-check-square-o"></i></span> Join this group</a>
      {% endif %}



</div>
</h1>
<p></p>
<h2> Member Count: {{group.members.count}}</h2>



{% endblock %}


{% block group_content %}


	{% if group.posts.count == 0 %}
  <p></p>
	<h2>No posts in this group yet!</h2>

	{% else %}
<p></p>
<h2>Group posts:</h2>
		{% for post in group.posts.all %}
			{% include "posts/_post.html" %}
		{% endfor %}

	{% endif %}

{% endblock %}

simplesocial/groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap3 %}

{% block body_block %}
<h4>Create a New Group</h4>
  <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}

	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			<a href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<h2>Groups</h2>

			<p>Welcome to the Groups Page! Select a Group with a shared interest!</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'groups:create' %}" class="btn btn-success"><span><i class="fa fa-plus-circle"></i></span> Create New Group!</a>
<p></p>
	{% endif %}

{% endblock %}

{% block group_content %}

	<div class="list-group">
		{% for group in object_list %}
		  <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
			     <h3 class="title list-group-item-heading">{{ group.name }}</h3>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}

						<span class="badge">{{ group.members.count }}</span> member{{ group.members.count|pluralize }}


						<span class="badge">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}


			</div>
		</a>
		{% endfor %}
	</div>

{% endblock %}